version: '3.4'
services:
  vite_docker:
    image: node:16.20.0
    container_name: encrypt-words-back
    entrypoint: /bin/sh
    ports:
      - 8081:8081
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true
